AWSTemplateFormatVersion: "2010-09-09"
Description: HTTP API Gateway that proxies requests to an EC2 backend

Parameters:
  BackendUrl:
    Type: String
    Description: "Base URL of backend WITHOUT trailing slash, e.g. http://3.122.247.91:3000"

Resources:

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: SimpleBackendProxy
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"

  HttpIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: HTTP_PROXY
      IntegrationMethod: ANY
      # Wichtig: Path weiterreichen!
      IntegrationUri: !Sub "${BackendUrl}/{proxy}"
      PayloadFormatVersion: "1.0"

  HttpRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "ANY /{proxy+}"
      Target: !Join [ "/", ["integrations", !Ref HttpIntegration] ]

  HttpStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: prod
      AutoDeploy: true

Outputs:
  ApiInvokeUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
